### ISSUE TITLE
Globalip Acceptancetest case is failing

### ISSUE THREAD

**Issue by Praveengostu** [softlayer/terraform-provider-softlayer#103]
With resource config
resource "virtual_guest" "vm1" {
    hostname = "vm1"
    domain = "example.com"
    os_reference_code = "DEBIAN_7_64"
    datacenter = "NY"
    network_speed = 100
    hourly_billing = true
    private_network_only = false
    cores = 1
    memory = 1024
    disks = [25]
    local_disk = false
}

resource "virtual_guest" "vm2" {
    hostname = "vm2"
    domain = "example.com"
    os_reference_code = "DEBIAN_7_64"
    datacenter = "NY"
    network_speed = 100
    hourly_billing = true
    private_network_only = false
    cores = 1
    memory = 1024
    disks = [25]
    local_disk = false
}

resource "global_ip" "test-global-ip" {
    routes_to = "${virtual_guest.vm1.ipv4_address}"
}

--- FAIL: TestAccSoftLayerGlobalIp_Basic (418.56s)
	testing.go:265: Step 0 error: After applying this step and refreshing, the plan was not empty:
So after applying and refreshing the plan return a DIFF where it it expecting to be empty

**Comment by renier** [comment]
@Praveengostu We don't have any test called `TestAccIBMCloudInfraGlobalIp_Basic`.
