### ISSUE TITLE
scale group acceptence test fails

### ISSUE THREAD

**Issue by hkantare** [softlayer/terraform-provider-softlayer#109]
with resource config

const testAccCheckSoftLayerScaleGroupConfig_basic = `
resource "softlayer_lb_local" "local_lb_01" {
    connections = 250
    datacenter = "sng01"
    ha_enabled = false
}

resource "softlayer_lb_local_service_group" "http_sg" {
    load_balancer_id = "${softlayer_lb_local.local_lb_01.id}"
    allocation = 100
    port = 80
    routing_method = "ROUND_ROBIN"
    routing_type = "HTTP"
}

resource "softlayer_scale_group" "sample-http-cluster" {
    name = "sample-http-cluster"
    regional_group = "as-sgp-central-1"
    cooldown = 30
    minimum_member_count = 1
    maximum_member_count = 10
    termination_policy = "CLOSEST_TO_NEXT_CHARGE"
    virtual_server_id = "${softlayer_lb_local_service_group.http_sg.id}"
    port = 8080
    health_check = {
        type = "HTTP"
    }
    virtual_guest_member_template = {
        hostname = "test-VM"
        domain = "example.com"
        cores = 1
        memory = 4096
        network_speed = 1000
        hourly_billing = true
        os_reference_code = "DEBIAN_7_64"
        local_disk = false
        disks = [25,100]
        datacenter = "sng01"
        post_install_script_uri = ""
        user_metadata = "#!/bin/bash"
    }
}`

const testAccCheckSoftLayerScaleGroupConfig_updated = `
resource "softlayer_lb_local" "local_lb_01" {
    connections = 250
    datacenter = "sng01"
    ha_enabled = false
}

resource "softlayer_lb_local_service_group" "http_sg" {
    load_balancer_id = "${softlayer_lb_local.local_lb_01.id}"
    allocation = 100
    port = 80
    routing_method = "ROUND_ROBIN"
    routing_type = "HTTP"
}

resource "softlayer_scale_group" "sample-http-cluster" {
    name = "changed_name"
    regional_group = "as-sgp-central-1"
    cooldown = 35
    minimum_member_count = 2
    maximum_member_count = 12
    termination_policy = "NEWEST"
    virtual_server_id = "${softlayer_lb_local_service_group.http_sg.id}"
    port = 9090
    health_check = {
        type = "HTTP-CUSTOM"
        custom_method = "GET"
        custom_request = "/healthcheck"
        custom_response = 200
    }
    virtual_guest_member_template = {
        hostname = "example-VM"
        domain = "test.com"
        cores = 2
        memory = 8192
        network_speed = 100
        hourly_billing = true
        os_reference_code = "CENTOS_7_64"
        local_disk = false
        disks = [25,100]
        datacenter = "sng01"
        post_install_script_uri = "http://localhost/index.html"
        user_metadata = "#!/bin/bash"
    }
}`

--- FAIL: TestAccSoftLayerScaleGroup_Basic (139.30s)
        testing.go:265: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: softlayer_scale_group.sample-http-cluster
                  virtual_guest_member_template.0.wait_time_minutes: "0" => "90"

                STATE:

**Comment by minsikl** [comment]
The fix has been applied.
