### ISSUE TITLE
softlayer Global Ip AT fails 

### ISSUE THREAD

**Issue by Praveengostu** [softlayer/terraform-provider-softlayer#116]
With latest pull i see multiple failures with AT for global ip
TestAccSoftLayerGlobalIp_Basic (3727.84s)
	testing.go:265: Step 2 error: Error applying: 1 error(s) occurred:
		
		* softlayer_global_ip.test-global-ip (destroy): 1 error(s) occurred:
		
		* softlayer_global_ip.test-global-ip: SoftLayer_Exception_Public: This cancellation could not be processed please contact support.This cancellation could not be processed please contact support. You cannot cancel the selected billing items immediately.  Please choose your next billing anniversary date for cancellation date. (HTTP 500)
	testing.go:329: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Error applying: 2 error(s) occurred:
		
		* softlayer_global_ip.test-global-ip-3 (destroy): 1 error(s) occurred:
		
		* softlayer_global_ip.test-global-ip-3: SoftLayer_Exception_Public: This cancellation could not be processed please contact support.This cancellation could not be processed please contact support. You cannot cancel the selected billing items immediately.  Please choose your next billing anniversary date for cancellation date. (HTTP 500)
		* softlayer_global_ip.test-global-ip (destroy): 1 error(s) occurred:
		
		* softlayer_global_ip.test-global-ip: SoftLayer_Exception_Public: This cancellation could not be processed please contact support.This cancellation could not be processed please contact support. You cannot cancel the selected billing items immediately.  Please choose your next billing anniversary date for cancellation date. (HTTP 500)
		
		State: softlayer_global_ip.test-global-ip:
		  ID = 57983
		  ip_address = 108.168.254.25
		  routes_to = 169.55.187.203
		
		  Dependencies:
		    softlayer_virtual_guest.vm2
		softlayer_global_ip.test-global-ip-3:
		  ID = 57985
		  ip_address = 2607:f0d0:0003:0026:0000:0000:0000:0000
		  routes_to = 2401:c900:1501:0046:0000:0000:0000:0003
		
		  Dependencies:
		    softlayer_virtual_guest.vm3
		softlayer_virtual_guest.vm2:
		  ID = 28869427
		  cores = 1
		  datacenter = tor01
		  dedicated_acct_host_only = false
		  disks.# = 1
		  disks.0 = 25
		  domain = example.com
		  hostname = vm2
		  hourly_billing = true
		  ip_address_id = 70758601
		  ip_address_id_private = 70759291
		  ipv4_address = 169.55.187.203
		  ipv4_address_private = 10.166.222.96
		  ipv6_enabled = false
		  local_disk = false
		  memory = 1024
		  network_speed = 100
		  notes = 
		  os_reference_code = DEBIAN_7_64
		  private_network_only = false
		  private_subnet = 10.166.222.64/26
		  private_vlan_id = 1528235
		  public_subnet = 169.55.187.192/28
		  public_vlan_id = 1528233
		  secondary_ip_addresses.# = 0
		  wait_time_minutes = 90
		softlayer_virtual_guest.vm4:
		  ID = 28869555
		  cores = 1
		  datacenter = che01
		  dedicated_acct_host_only = false
		  disks.# = 1
		  disks.0 = 25
		  domain = example.com
		  hostname = vm4
		  hourly_billing = true
		  ip_address_id = 70759211
		  ip_address_id_private = 70759463
		  ipv4_address = 169.38.82.154
		  ipv4_address_private = 10.162.99.131
		  ipv6_address = 2401:c900:1501:0046:0000:0000:0000:0002
		  ipv6_address_id = 70759227
		  ipv6_enabled = true
		  local_disk = false
		  memory = 1024
		  network_speed = 100
		  notes = 
		  os_reference_code = DEBIAN_7_64
		  private_network_only = false
		  private_subnet = 10.162.99.128/26
		  private_vlan_id = 1528239
		  public_ipv6_subnet = 2401:c900:1501:0046:0000:0000:0000:0000/64
		  public_subnet = 169.38.82.144/28
		  public_vlan_id = 1528237
		  secondary_ip_addresses.# = 0
		  wait_time_minutes = 90
FAIL
FAIL	github.com/softlayer/terraform-provider-softlayer/softlayer	3729.473s

**Comment by renier** [comment]
Please try tomorrow. This error is given by the API if you cancel a monthly resource on the last day of the month that was just created..
