### ISSUE TITLE
Global IP acceptance testcase fails 

### ISSUE THREAD

**Issue by Praveengostu** [softlayer/terraform-provider-softlayer#119]
After pulling the latest code the global IP AT fails with below error
FAIL: TestAccSoftLayerGlobalIp_Basic (386.23s)
	testing.go:265: Step 0 error: Error applying: 1 error(s) occurred:
softlayer_virtual_guest.vm1: 1 error(s) occurred:
		
		* softlayer_virtual_guest.vm1: Error retrieving virtual guest: Get https://api.softlayer.com/rest/v3/SoftLayer_Virtual_Guest/28960471.json?objectMask=mask%5Bhostname%2Cdomain%2CstartCpus%2CmaxMemory%2CdedicatedAccountHostOnlyFlag%2CprimaryIpAddress%2CprimaryBackendIpAddress%2CprivateNetworkOnlyFlag%2ChourlyBillingFlag%2ClocalDiskFlag%2Cnotes%2CuserData%5Bvalue%5D%2CtagReferences%5Bid%2Ctag%5Bname%5D%5D%2Cdatacenter%5Bid%2Cname%2ClongName%5D%2CprimaryNetworkComponent%5BnetworkVlan%5Bid%5D%2CprimaryVersion6IpAddressRecord%5Bsubnet%2CguestNetworkComponentBinding%5BipAddressId%5D%5D%2CprimaryIpAddressRecord%5Bsubnet%2CguestNetworkComponentBinding%5BipAddressId%5D%5D%5D%2CprimaryBackendNetworkComponent%5BnetworkVlan%5Bid%5D%2CprimaryIpAddressRecord%5Bsubnet%2CguestNetworkComponentBinding%5BipAddressId%5D%5D%5D%5D: dial tcp 66.228.119.120:443: i/o timeout

I had set the SOFTLAYER_TIMEOUT to 600

**Comment by minsikl** [comment]
The TCP timeout error means there is a problem with the connection at the network socket level. Please check the network connection of the test environment and perform the test.
