### ISSUE TITLE
image template AT fails

### ISSUE THREAD

**Issue by Praveengostu** [softlayer/terraform-provider-softlayer#121]
=== RUN   TestAccSoftLayerImageTemplateDataSource_Basic
--- FAIL: TestAccSoftLayerImageTemplateDataSource_Basic (2.62s)
	testing.go:265: Step 0 error: Error refreshing: 1 error(s) occurred:
		
		* data.softlayer_image_template.tfacc_img_tmpl: 1 error(s) occurred:
		
		* data.softlayer_image_template.tfacc_img_tmpl: data.softlayer_image_template.tfacc_img_tmpl: Could not find image template with name [jumpbox]
FAIL
FAIL	github.com/softlayer/terraform-provider-softlayer/softlayer	4.258s

**Comment by renier** [comment]
Yes, the image name has to exist in the account being tested.

**Comment by Praveengostu** [comment]
@renier If that is the case it should be a prerequisite.. The AT should not fail .. Is this depends on other tests which create the image jumpbox?

**Comment by renier** [comment]
@Praveengostu Even if we set up a precheck function, the tests are pass/fail.

It does not depend on other tests. The private (or shared) image with that name should exist for it to pass.
