### ISSUE TITLE
firewall AT fails 

### ISSUE THREAD

**Issue by Praveengostu** [softlayer/terraform-provider-softlayer#124]
==> Checking that code complies with gofmt requirements...
go tool vet -all .
TF_ACC=1 go test $(go list ./... | grep -v '/vendor/') -v -run=TestAccSoftLayerFwHardwareDedicated_Basic -timeout 120m
?   	github.com/softlayer/terraform-provider-softlayer	[no test files]
=== RUN   TestAccSoftLayerFwHardwareDedicated_Basic
--- FAIL: TestAccSoftLayerFwHardwareDedicated_Basic (419.27s)
	testing.go:265: Step 0 error: Error applying: 1 error(s) occurred:
		
		* softlayer_fw_hardware_dedicated.accfw: 1 error(s) occurred:
		
		* softlayer_fw_hardware_dedicated.accfw: Error during creation of dedicated hardware firewall: couldn't find resource (21 retries)
FAIL
FAIL	github.com/softlayer/terraform-provider-softlayer/softlayer	421.422s

Could you please help me understand what is the issue with this which i have not seen this earlier

**Comment by renier** [comment]
This passes for me.

```
==> Checking that code complies with gofmt requirements...
go tool vet -all .
TF_ACC=1 go test $(go list ./... | grep -v '/vendor/') -v -run TestAccSoftLayerFwHardwareDedicated_Basic -timeout 120m
?   	github.com/softlayer/terraform-provider-softlayer	[no test files]
=== RUN   TestAccSoftLayerFwHardwareDedicated_Basic
--- PASS: TestAccSoftLayerFwHardwareDedicated_Basic (341.47s)
PASS
ok  	github.com/softlayer/terraform-provider-softlayer/softlayer	342.551s
```

@minsikl Any ideas? Since they are using their own account for this, maybe it is something they don't have in their account?

**Comment by minsikl** [comment]
@Praveengostu Please check if the test user has `Hardware Firewall` permission.
