### ISSUE TITLE
User AT fails even the password as per the constraint

### ISSUE THREAD

**Issue by Praveengostu** [softlayer/terraform-provider-softlayer#125]
testing.go:265: Step 0 error: Error applying: 1 error(s) occurred:
		
		* softlayer_user.testuser: 1 error(s) occurred:
		
		* softlayer_user.testuser: Error creating SoftLayer User: SoftLayer_Exception_User_Customer_Password_Complexity_Failed: Invalid password: Passwords must contain an uppercase letter. (HTTP 500)

The password already contains a upper case still it complains as above

**Comment by renier** [comment]
Passing for me,
```
==> Checking that code complies with gofmt requirements...
go tool vet -all .
TF_ACC=1 go test $(go list ./... | grep -v '/vendor/') -v -run TestAccSoftLayerUser_Basic -timeout 120m
?   	github.com/softlayer/terraform-provider-softlayer	[no test files]
=== RUN   TestAccSoftLayerUser_Basic
--- PASS: TestAccSoftLayerUser_Basic (18.36s)
PASS
ok  	github.com/softlayer/terraform-provider-softlayer/softlayer	18.946s
```

**Comment by minsikl** [comment]
@Praveengostu It looks like that your user id does not have a privilege to manage users. Please make sure your user id has `Add New User` privilege.
