### ISSUE TITLE
Multiple SSH keys with the same fingerprint create problems during resource destroy

### ISSUE THREAD

**Issue by rbmateescu** [softlayer/terraform-provider-softlayer#128]
If the same SSH public key is deployed multiple times, it appears that only one instance of that SSH key is created in SL. This creates problems when deleting resources that no longer exists. Here are the steps to reproduce this problem:
1. Deploy a template (tf1) that contains a pub SSH key (key1) and a VM (vm1)
2. Deploy a template (tf2) that contains the same pub SSH key (key1) and associate it with another VM (vm2)
3. Destroy tf2. The destroy goes through fine.
4. Destroy tf1. The following error is reported:
softlayer_ssh_key.orpheus_public_key: Refreshing state... (ID: 815031)
softlayer_virtual_guest.debian_small_virtual_guest: Refreshing state... (ID: 29409507)
softlayer_virtual_guest.debian_small_virtual_guest: Destroying...
softlayer_virtual_guest.debian_small_virtual_guest: Still destroying... (10s elapsed)
softlayer_virtual_guest.debian_small_virtual_guest: Destruction complete
softlayer_ssh_key.orpheus_public_key: Destroying...
Error applying plan:
1 error(s) occurred:

softlayer_ssh_key.orpheus_public_key: Error deleting SSH key: SoftLayer_Exception_ObjectNotFound: Unable to find object with id of '815031'. (HTTP 404)
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by renier** [comment]
@rbmateescu Hi Radu. Yes, on purpose, the resource will attach itself to an existing matching key (by ssh key fingerprint) in the cloud, to avoid duplicate keys. SoftLayer will complain with an error if you try to create the same key twice, and we avoid that this way.

What we can do is to not report an error if the key is not found upon deletion. Would that work for you? Also @minsikl @riethm

**Comment by rbmateescu** [comment]
Thanks Renier, yes, I think that would solve our immediate problem with the overall status of the destroy.

**Comment by renier** [comment]
@rbmateescu We could ask, why are you creating the same exact key from two different configs? Why not create in one, and use a [data source](https://github.com/softlayer/terraform-provider-softlayer/blob/master/docs/datasources/softlayer_ssh_key.md) from the other?

**Comment by rbmateescu** [comment]
These provisioning actions are part of a stress suite that deploys the same template and provide some metrics on the platform response times. In other words, the more resources created, the more relevant the test results. And SSH keys being one of the few free resources in SL, it was included in each template.

**Comment by renier** [comment]
@rbmateescu I'm inclining towards leaving the code how it is. I don't think we should hide an error when something unexpected happens. Could cause other problems in other use cases.

It looks like the stress suite is re-using the same key across. It could be tweaked to generate unique keys for each instance maybe?
