### ISSUE TITLE
Clarify destruction of monthly resources

### ISSUE THREAD

**Issue by athak** [softlayer/terraform-provider-softlayer#133]
When cancelling monthly resources from the panel, one has the option to choose if the the resource is cancelled immediately or on the account anniversary date.

When a monthly resource is destroyed in terraform, is it cancelled immediately or on the anniversary date? From previous tests, I assume it's on the anniversary date but wanted to confirm.

Thanks,
Atha

**Comment by renier** [comment]
https://github.com/softlayer/terraform-provider-softlayer/blob/master/softlayer/resource_softlayer_virtual_guest.go#L910

http://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/deleteObject

Destruction of virtual guests is effective immediatedly.

Same goes for bare metals.

https://github.com/softlayer/terraform-provider-softlayer/blob/master/softlayer/resource_softlayer_bare_metal.go#L432-L434

http://sldn.softlayer.com/reference/services/SoftLayer_Billing_Item/cancelItem

**Comment by athak** [comment]
@renier thanks for the prompt reply. Would be great if it was configurable. As it is, we either have to wait for the anniversary date or cancel via panel and then perform state surgery to remove the cancelled servers.

**Comment by renier** [comment]
@athak Yes. Please open an issue for making it configurable, or you can re-title this one and reopen.
