### ISSUE TITLE
`softlayer_file_storage` requires a different IOPS value than what is stored in state

### ISSUE THREAD

**Issue by lgfa29** [softlayer/terraform-provider-softlayer#135]
When ordering a `softlayer_file_storage` resource you need to specify a value for `iops` which can be `0.25`, `2`, `4` or `10`.

But after the resource is created, the value stored in the Terraform state has more decimals, so, for example,`4` is stored as `4.096` and `10` is stored as `10.24`.

This causes a subsequent `terraform plan`  to incorrect flag the resource as needing to be recreated.

### Steps to reproduce
1. Order a `softlayer_file_storage`:
```hcl
resource "softlayer_file_storage" "nfs" {
    type = "Endurance"
    datacenter = "tor01"
    capacity = 500
    iops = 4
}
```

2. `terraform apply`
3. `terraform plan` gives wrong result:
```
/+ softlayer_file_storage.nfs
    capacity:                           "500" => "500"
    datacenter:                         "tor01" => "tor01"
    hostname:                           "[OMITTED]" => "<computed>"
    iops:                               "4.096" => "4" (forces new resource)
    snapshot_capacity:                  "500" => "500"
    type:                               "Endurance" => "Endurance"
    volumename:                         "[OMITTED]" => "<computed>"
```

### Expected result
No changes required

### Environment
```
Terraform v0.8.8
terraform-provider-softlayer v1.4.0
```

**Comment by renier** [comment]
@ivan-n16
