### ISSUE TITLE
Binaries built with Terraform 0.9.X

### ISSUE THREAD

**Issue by jvrplmlmn** [softlayer/terraform-provider-softlayer#137]
Hello @renier, I believe that you're one of the current maintainers of this repository.

Is the provider compatible with Terraform 0.9.X? If so, is there any plans to build and provide new binaries? Let me know if the codebase requires some adaptations to be compatible with `0.9.X`, I might be able to provide some man hours to help.

**Comment by renier** [comment]
@jvrplmlmn Please try release 1.5.0
