### ISSUE TITLE
Removing all tags from instance/baremetal does not work

### ISSUE THREAD

**Issue by athak** [softlayer/terraform-provider-softlayer#139]
When trying to remove all tags from an instance or baremetal server, the operation appears to complete successfully but the tags are not removed.

As long as there is at least one tag left, tags are removed without issue. It is only when all tags are removed that is the issue. We have to remove the tags using slcli.

Thanks,
Atha

**Comment by jvrplmlmn** [comment]
According to this https://github.com/softlayer/softlayer-go/blob/58a39b003905ea63e4ad9bbfc48b3c9abfcea0bb/services/tag.go#L114

> // (...) To remove all tag references pass an empty string. (...)

We should be able to fix this by removing this conditionals:

https://github.com/softlayer/terraform-provider-softlayer/blob/8deb988f3241f273c4031292a0ded8a7c19f101d/softlayer/resource_softlayer_bare_metal.go#L529

https://github.com/softlayer/terraform-provider-softlayer/blob/8deb988f3241f273c4031292a0ded8a7c19f101d/softlayer/resource_softlayer_virtual_guest.go#L1117
