### ISSUE TITLE
Support virtual guests with IPV6

### ISSUE THREAD

**Issue by fuzzyami** [softlayer/terraform-provider-softlayer#15]
We would like to spin up lots and lots of hosts with IPV6. The feature is woefully missing from the original terraform plugin for SL. It is supported in this version?

thanks!

**Comment by renier** [comment]
@fuzzyami This is not available yet.

**Comment by fuzzyami** [comment]
Thanks for the prompt reply. This seriously inhibits our ability to deploy hosts at large scale.

**Comment by minsikl** [comment]
SoftLayer vm supports an IPv6 address for public network. The following arguments can be added to a schema of a virtual guest.
```
			"ipv6_address": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"ip_address_id6": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"public_subnet6": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
				Computed: true,
			},
```

**Comment by minsikl** [comment]
Public IPv6 address feature has been added to virtual guests and the issue can be closed.
