### ISSUE TITLE
'fixed_config_preset' forced required breaks 'import'

### ISSUE THREAD

**Issue by cbrinker** [softlayer/terraform-provider-softlayer#153]
The 'fixed_config_preset' option on bare_metal resource is preventing me from importing my pre-existing resources into the terraform state file.

https://github.com/softlayer/terraform-provider-softlayer/blob/master/softlayer/resource_softlayer_bare_metal.go#L157

The core problem is that when I issue a `terraform import softlayer_bare_metal.aname ID`  the entry that is imported contains an empty string. When I attempt to adjust this by filling in a value in a .tf file, leads to `terraform plan` deciding it needs to force a new resource:

```
    fixed_config_preset:  "" => "S1270_32GB_1X1TBSATA_NORAID" (forces new resource)
```

The underlying API doesn't look to have this as a required variable: http://sldn.softlayer.com/reference/services/SoftLayer_Hardware/createObject so, can we relax this validation?

**Comment by athak** [comment]
@cbrinker we have left that parameter as "" in our .tf files without issues.

**Comment by renier** [comment]
@cbrinker Only bare metals with a fixed config preset are supported currently.

Does athak's fix work for you?

**Comment by cbrinker** [comment]
@renier yes, specifying an empty string does allow terraform to function. Can this workaround be added to the documentation so future users don't hit the same problem?

Thanks,
Chris

**Comment by renier** [comment]
marking as a FAQ to allow others to filter on and find in the future.
