### ISSUE TITLE
Upcoming Provider Changes in Terraform 0.10

### ISSUE THREAD

**Issue by jvrplmlmn** [softlayer/terraform-provider-softlayer#159]
Hashicorp recently announced the following: [Upcoming Provider Changes in Terraform 0.10](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/)

Changelog: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0100-beta1-unreleased

> Terraform providers are no longer distributed as part of the main Terraform distribution. Instead, they are installed automatically as part of running terraform init. It is therefore now mandatory to run terraform init before any other operations that use provider plugins, to ensure that the required plugins are installed and properly initialized.

How will this affect the development of this provider? Will it be migrated to https://github.com/terraform-providers/terraform-provider-softlayer ?

**Comment by renier** [comment]
That will be taken care off when we merge/transform into the terraform-provider-ibm in the near future (this year)
