### ISSUE TITLE
Is there a way to order performance / endurance storage here that I'm missing?

### ISSUE THREAD

**Issue by gkrash** [softlayer/terraform-provider-softlayer#162]
I don't think I see a way to do this easily here (outside of using a null resource, and running a local shell command to procure the disk).  Both need to be able to procure disk in general, as well as "assign" it to specific resources..

Is there a different suggested method here?

  Thanks..

**Comment by athak** [comment]
@gkrash there are `softlayer_block_storage` and `softlayer_file_storage` resources that should do what are you are asking for.

**Comment by gkrash** [comment]
I was hoping I was just being dense :) - thanks for the pointer @ the resources.  - I was looking for storage, not block storage - must have been staring at my screen for too long.  

Thanks again for the help!
