### ISSUE TITLE
Can't seem to set ipv4_address_private in softlayer_virtual_guest

### ISSUE THREAD

**Issue by Clarabridge-Jeff-Johnston** [softlayer/terraform-provider-softlayer#163]
softlayer_virtual_guest.$resource: "ipv4_address_private": this field cannot be set

It appears looking at the code it won't let me set it, despite the terraform documentation saying very much the opposite at https://www.terraform.io/docs/providers/softlayer/r/virtual_guest.html

Is there any chance at getting this implemented or was it torn out due to causing some issues?  Did it never work?

I have an NFS resource that depends on private v4 addresses, and the host provisioning depends on the mountpoint variable of the NFS resource.  How would I provision two hosts and NFS storage in one 'apply' action?...  I was hoping on setting the IP address statically but it appears that isn't going to be an option.

**Comment by Clarabridge-Jeff-Johnston** [comment]
I got around it using null resources and ssh connection FWIW.  Maybe reach out to the terraform people and tell them their documentation is out of date.

**Comment by renier** [comment]
Yes, that field is read only. See https://github.com/softlayer/terraform-provider-softlayer/blob/master/docs/resources/softlayer_virtual_guest.md. The docs at terraform.io are outdated and have errors.

We are moving over to a new provider repo that should allow you to provision two hosts and an NFS storage in one apply action: https://github.com/IBM-Bluemix/terraform-provider-ibm
