### ISSUE TITLE
Terraform destroys incompleted SL virtual guest if re-run 'terraform apply' after Timeout error

### ISSUE THREAD

**Issue by bondyk** [softlayer/terraform-provider-softlayer#21]
If creating a new virtual guest takes more than 10 minutes then terraform exits with timeout error and SoftLayer continues creating server. When re-run 'terraform apply' then after refreshing the state it starts destroying that instance and creates a new one afterwards. 
## Steps to reproduce
- Create softlayer_virtual_guest resource with reference to private image.
- Run 'terraform apply' and wait 10 minutes to get Timeout Error
  `softlayer_virtual_guest.data-node: Error waiting for virtual machine (24773585) to become ready: timeout while waiting for state to become 'idle' (last state: 'active', timeout: 10m0s)`
- Re-run 'terraform apply' and check output
## Expected result

Terraform shouldn't initiate destroying instance but should wait for completion instead.
## Actual result

Terraform initiates destroying of the incompletely created virtual guest and then creating a new one
### softlayer.tf

```
data "softlayer_image_template" "private_redhat" {
    name = "Private virtual RedHat 6.7 2016-6-22"
}

resource "softlayer_virtual_guest" "data-node" {
    name = "${var.dn_name}"
    domain = "${var.dn_domain}"
    datacenter = "${var.dn_region}"
    hourly_billing = "${var.dn_hourly_billing}"
    private_network_only = "${var.dn_private_network_only}"
    network_speed = "${var.dn_public_network_speed}"
    cpu = "${var.dn_cpu}"
    ram = "${var.dn_ram}"
    local_disk = "${var.dn_local_disk}"

    front_end_vlan {
       id = "${var.dn_frontend_vlan_id}"
    }
    back_end_vlan {
       id = "${var.dn_backend_vlan_id}"
    }

    image_id = "${data.softlayer_image_template.private_redhat.id}"
}
```
### Output

```
me> terraform apply
data.softlayer_image_template.private_redhat: Refreshing state...
softlayer_virtual_guest.data-node: Creating...
softlayer_virtual_guest.data-node: Still creating... (10s elapsed)
...
softlayer_virtual_guest.data-node: Still creating... (10m0s elapsed)
Error applying plan:

1 error(s) occurred:

* softlayer_virtual_guest.data-node: Error waiting for virtual machine (24773585) to become ready: timeout while waiting for state to become 'idle' (last state: 'active', timeout: 10m0s)

me> terraform apply
data.softlayer_image_template.private_redhat: Refreshing state...
softlayer_virtual_guest.data-node: Destroying...
softlayer_virtual_guest.data-node: Still destroying... (10s elapsed)
...
softlayer_virtual_guest.data-node: Destruction complete
softlayer_virtual_guest.data-node: Creating...
softlayer_virtual_guest.data-node: Still creating... (6s elapsed)
softlayer_virtual_guest.console: Still creating... (10m6s elapsed)
Error applying plan:

1 error(s) occurred:

* softlayer_virtual_guest.data-node: Error waiting for virtual machine (24773585) to become ready: timeout while waiting for state to become 'idle' (last state: 'active', timeout: 10m0s)
```

**Comment by riethm** [comment]
@bondyk, can you post the output of `terraform plan`, after the initial failure, but before re-running `terraform apply`?

**Comment by bondyk** [comment]
Output of 'terraform plan'

```
data.softlayer_image_template.private_redhat: Refreshing state...
softlayer_virtual_guest.data-node: Refreshing state... (ID: 24776441)

-/+ softlayer_virtual_guest.data-node
    back_end_subnet:                        "10.122.218.192/26" => "<computed>"
    back_end_vlan.%:                        "3" => "1" (forces new resource)
    back_end_vlan.id:                       "559111" => "559111"
    back_end_vlan.primary_router_hostname:  "bcr01a.tor01" => ""
    back_end_vlan.vlan_number:              "1462" => ""
    cpu:                                    "2" => "2"
    datacenter:                             "tor01" => "tor01"
    domain:                                 "mydomain.com" => "mydomain.com"
    front_end_subnet:                       "123.35.69.80/28" => "<computed>"
    front_end_vlan.%:                       "3" => "1" (forces new resource)
    front_end_vlan.id:                      "559102" => "559102"
    front_end_vlan.primary_router_hostname: "fcr01a.tor01" => ""
    front_end_vlan.vlan_number:             "779" => ""
    hourly_billing:                         "true" => "true"
    image_id:                               "1172739" => "1172739"
    ip_address_id:                          "21908014" => "<computed>"
    ip_address_id_private:                  "30273956" => "<computed>"
    ipv4_address:                           "123.35.69.87" => "<computed>"
    ipv4_address_private:                   "10.122.218.144" => "<computed>"
    local_disk:                             "false" => "false"
    name:                                   "data-node-1" => "data-node-1"
    network_speed:                          "10" => "10"
    private_network_only:                   "false" => "false"
    ram:                                    "2048" => "2048"


Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by renier** [comment]
I'm going to increase the timeout. Also, I'm going to make sure that the Id is not saved until after we  are done waiting for the creation to complete. That way, if it were to timeout again, it won't have any ID in play yet that would make it destroy an existing VM, at the least.

**Comment by riethm** [comment]
@bondyk I think the problem here is that we don't (yet) support specifying the vlan ID in the virtual_guest configuration:

``` hcl
    front_end_vlan {
       id = "${var.dn_frontend_vlan_id}"
    }
    back_end_vlan {
       id = "${var.dn_backend_vlan_id}"
    }
```

You have to specify the vlan number and primary_router_hostname for each:

``` hcl
    front_end_vlan {
      vlan_number = 779
      primary_router_hostname = "fcr01a.tor01"
    }
    back_end_vlan {
      vlan_number = 1462
      primary_router_hostname = "bcr01a.tor01"
    }
```

(assuming these are the values you intended)

Because you are specifying the (optional) vlan sections, but not providing any of the recognized map keys, terraform is interpreting as a difference between cloud and config, and forcing a new resource.

I believe increasing the timeouts may be a good idea, but should consider leaving the logic to set the ID as it was, so that TF apply won't try to provision a new VM (in the event that even the new timeout is exceeded)

**Comment by renier** [comment]
@riethm, why isn't terraform complaining when you provide a value out of schema then?

**Comment by riethm** [comment]
@renier Good question.  I guess that it is because the vlan schema elements are map types, and terraform only validates known map keys.  And unfortunately, it doesn't limit to the same set when computing diffs.

**Comment by renier** [comment]
@riethm, about when to set the ID, in the case of a timeout, do you think how it is now it will not do a force new of the resource on a subsequent refresh/apply?

**Comment by riethm** [comment]
It shouldn't, so long as:
1. By the time the ID is available/set, all other attributes of the virtual_guest could be retrieved from the API on a subsequent refresh/apply (pretty sure this is true - when we have an ID from SL, the full virtual_guest object is available in the API)
2. There is nothing in the configuration which would artificially force a new resource (e.g., an unknown map key)

**Comment by renier** [comment]
@riethm, ok, so I'll close the PR and let's wait to see what happens when the correct properties are used.

**Comment by bondyk** [comment]
@riethm I've just tested with specified vlan number and router hostname. After timeout failure terraform doesn't see any changes to trigger update or destroy of the resource and exits successfully. But it still doesn't show that the resource creation is in progress (it's not so bad though).
