### ISSUE TITLE
softlayer_image_template datasource only supports private images

### ISSUE THREAD

**Issue by Ari-E-S** [softlayer/terraform-provider-softlayer#28]
I tracked the limitation all the way to softlayer-go 
vendor/github.com/softlayer/softlayer-go/services/account.go, line 470:

``` go
// Retrieve Private template group objects (parent and children) and the shared template group objects (parent only) for an account.
func (r Account) GetBlockDeviceTemplateGroups() (resp []datatypes.Virtual_Guest_Block_Device_Template_Group, err error) {
        err = r.Session.DoRequest("SoftLayer_Account", "getBlockDeviceTemplateGroups", nil, &r.Options, &resp)
        return
}
```

Is there any support planed for public images?

**Comment by renier** [comment]
@arielsalvo, yes, we can do that. I see that [this](http://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest_Block_Device_Template_Group/getPublicImages) exists, so we'd have to add a call to that.

**Comment by Ari-E-S** [comment]
Sorry.... Didn't have much chance to test this until now.

Seems it doesn't get to the new code because of lines 48-50

**Comment by renier** [comment]
@arielsalvo ah, sorry. should work now.
