### ISSUE TITLE
Ability to return network info

### ISSUE THREAD

**Issue by pat610** [softlayer/terraform-provider-softlayer#30]
It would be great if this provider was able to return some extra network information.  Currently I have to make a separate API call to get it.

https://$user:$apiKey@api.softlayer.com/rest/v3/SoftLayer_Virtual_Guest/$vsiId/getBackendNetworkComponents?objectMask=mask[primarySubnet[gateway,netmask]]

Method: Get

**Comment by renier** [comment]
@pat610 That information is not useful for interpolation into other resources. It would only be useful for a human to see on `terraform show`, but why not use the portal in that case?

**Comment by dnwe** [comment]
I thought you could already achieve this in the outputs?

e.g.,

```
output "vm_ips" {
  value = "${join(",", softlayer_virtual_guest.*.ipv4_address)}"
}
```

**Comment by pat610** [comment]
In our use case we are kicking off an Ansible playbook that installs some software on the vm.  One of the inputs the software requires is this network information.  The whole process is automated.

@dnwe We are already using outputs to get the ipv4_address as well as some other fields (id, name, domain) but gateway and subnet mask are not available.

**Comment by renier** [comment]
@pat610, so the gateway and netmask can be obtained from `ifconfig` output on the system by Ansible, right?

**Comment by dnwe** [comment]
Yeah aren't these in the network facts that ansible gathers itself for each host during setup?

**Comment by pat610** [comment]
I'm using red hat 7.  ifconfig is deprecated.  It would be easier if I could just get it from terraform the same way I get it through the API.  I don't want to have to deal with parsing output.

**Comment by renier** [comment]
@pat610 Ok, so `ip addr show`. Terraform is not meant to be another SoftLayer client library, exposing every field known on the docs, just in case. Any field we expose is primarily because it can be used by other resources, and secondarily because it is obviously essential for post-provisioning. This one is not looking like like it fits any of those cases.

**Comment by pat610** [comment]
Ok, I will use one of the other suggested solutions then.  Thanks!
