### ISSUE TITLE
Ability to return virtual guest password

### ISSUE THREAD

**Issue by pat610** [softlayer/terraform-provider-softlayer#31]
It would be great to be able to retrieve this from the provider.  Currently I'm retrieving it through the API.

```
def _get_password(self, console_id):

        try:

            response = self.client.call('Virtual_Guest', 'getSoftwareComponents', id=console_id, mask="id")

            software_id = response[0]['id']

            response = self.client.call('Software_Component', 'getPasswords', id=software_id, mask="password")

            return response[0]['password']

        except SoftLayer.exceptions.SoftLayerAPIError as ex:

            print 'Failed to retrieve password from SoftLayer:\n%s' % ex
```

**Comment by renier** [comment]
@pat610 Same counter-argument as with #30. Not useful to inform other resources, but useful for a human to read after _apply_ or _show_. But then, why not use the portal for that, if a human is the reader?

**Comment by renier** [comment]
Also, highly insecure to just display the password on screen

**Comment by pat610** [comment]
We are automating Terraform and passing the password on to an Ansible playbook.  The ansible playbook requires the password as part of the software installation.

**Comment by renier** [comment]
@pat610 It would be easier to provision the VM with ssh public keys, with Ansible holding the private key necessary to access those password-less.

**Comment by pat610** [comment]
We are using ssh public keys.  Ansible is able to connect without a password.  The password is needed by our software installation.  The software heavily modifies the vm including resetting the root password, I need to pass in this password so the root password matches what is specified in the portal.

**Comment by dnwe** [comment]
@pat610 why not just take a backup of /etc/shadow in ansible before you run this software installation and then restore /etc/shadow afterwards?

**Comment by renier** [comment]
@pat610 I see. This seems like a very special case. Don't think it is enough to add it in terraform.

I don't see how making the password in the portal match what is on the system would be desirable (potentially to keep your snippet above working?). It implies that even though you are using ssh keys, there are other things that will need the password to login, which is not so good. Can't those other things also use ssh keys?

Sorry for all the [why?s](https://en.wikipedia.org/wiki/5_Whys), but it helps to get down to the root reason for the request and its importance.

**Comment by pat610** [comment]
@renier We want the portal password to match the system password so that operations can look up the password for the system in the portal.  

@dnwe Probably a better way to go about it.  Thanks.

Thanks for the help guys, can probably close this issue.
