### ISSUE TITLE
Getting Started with Dev

### ISSUE THREAD

**Issue by Freyert** [softlayer/terraform-provider-softlayer#37]
Hasn't been a very straightforward experience, some of it is probably within the scope of the project to control others were probably some oddities with Go that I need to get over.
### README Steps

If I follow the README word for word I end up with this error:

```
Stderr: main.go:5:2: cannot find package "github.com/softlayer/terraform-provider-softlayer/softlayer" in any of:
    /usr/local/go/src/github.com/softlayer/terraform-provider-softlayer/softlayer (from $GOROOT)
    /home/fbyrne/gowork/src/github.com/softlayer/terraform-provider-softlayer/softlayer (from $GOPATH)
```

Which is expected because none of the directions instruct you to clone this directory into your $GOPATH following the Go package convention. Something an up to speed Go developer would understand, but even then one might expect the `Makefile` to handle this issue for us.

If I manually correct this problem I run into permission errors because the [`Makefile` step](https://github.com/softlayer/terraform-provider-softlayer/blob/master/scripts/build.sh#L22-L26) tries to copy the binary into a directory it doesn't have permission for. The OSX specific logic at the bottom seems kind of like a "what if I'm running X" issue which doesn't sound like fun to get into. 

My thought is that it would be _much_ simpler to just compile the binaries and then ask/suggest the user to point Terraform to that binary as described [here](https://www.terraform.io/docs/plugins/basics.html) and in the current README. It would provide consistent and flexible behavior for developers.

This would probably break the `make bin` step so `make dev` might be a good option to add.
### What I did to get around this

Instead of leveraging the Makefile, I went around it and did things the plain Go way:

```
#Set the $GOPATH and add Go binaries to $PATH
export GOPATH=$(pwd); \
export PATH="$PATH:$GOPATH/bin"

#Clone project into $GOPATH as a Go Package.
mkdir -p $GOPATH/src/github.com/softlayer/; \
git clone <REPO_URL> $GOPATH/src/github.com/softlayer/

#Download dependencies (-d only [downloads](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies))
go get -d ./...
#You may also have to manually download missing dependencies one by one if you get errors.
#golang.org/x typically would not resolve dependencies.

#Install the terraform-provider-softlayer (builds binary for your architecture)
go install github.com/softlayer/terraform-provider-softlayer

#Point terraform at the binary.
```

Unfortunately this avoids all the tools this repository uses at the moment. Which is probably a problem.
### Dev Terraform

README also should encourage developers to use the version of `terraform` that `go install` creates.

**Comment by renier** [comment]
@Freyert You seem to be doing all right, despite initial frustration with Go paths, etc. As I heard one professor say once "nothing furthers education like frustration".

The instructions say how to install the provider, before the development setup section. Had this step been done, you would not have gotten the error. You think this should be reiterated in the development setup section?

Once you have installed the library, you can further develop it from the location it was checked out under, which will be $GOPATH/src/github.com/softlayer/terraform-provider-softlayer.

If you need to fork it to submit a PR, you get into common git fundamentals knowledge. i.e. creating the fork, adding the remote to the existing local repo, and fetching/switching to the appropriate branches.

About your issue with `make bin`, not sure I understand. The code will just place the binary under $GOPATH/bin by default. So as long as $GOPATH is set, it should be fine... also why wouldn't it have write access to it? Where is your GOPATH? It should be something you have write access to, and not some general system location.

**Comment by Freyert** [comment]
@renier yes I think you've taken care of most of the problems. As a novice Go developer it wasn't clear to me that Go would preserver the version control data. That's a pretty nifty feature.

Thanks for the quick turn around!
