### ISSUE TITLE
Ordering Network_Storage

### ISSUE THREAD

**Issue by Freyert** [softlayer/terraform-provider-softlayer#41]
External network storage is a key component in cloud architecture, being able to orchestrate ISCSi ordering would be extremely useful.

Unfortunately, none of the [Network_Storage](https://sldn.softlayer.com/reference/services/SoftLayer_Network_Storage) objects support the `createObject` method and therefore require interaction with the  [`Product_Order::placeOrder`](http://developer.softlayer.com/reference/services/SoftLayer_Product_Order/placeOrder) service (I believe).

The issue here though is that this will be:
1. A common problem to solve for a variety of other SoftLayer services missing the `createObject` method.
2. When those services implement the `createObject` method it would be best to deprecate the complex `Product_Order::placeOrder` flow in favor of `createObject`.

Perhaps that's an issue for `softlayer-go`, but I imagine it would be something along the lines of creating a function for each of these resource with the signature:

```
func (r Network_Storage) createObject(templateObject *datatypes.Network_Storage_Request) (resp datatypes.Network_Storage_Request, err error) {
 //Craft container order
 //Product_order::placeOrder
}
```

---

In terraform the resource properties would originally focus on implementing:
1. [`allow_ips`](http://developer.softlayer.com/reference/services/SoftLayer_Network_Storage_Iscsi/allowAccessFromIpAddressList)
2. [`allow_subnets`](http://developer.softlayer.com/reference/services/SoftLayer_Network_Storage_Iscsi/allowAccessFromSubnetList)
3. [`allow_virtual_guests`](http://developer.softlayer.com/reference/services/SoftLayer_Network_Storage_Iscsi/allowAccessFromVirtualGuestList)
4. [`snapshot_schedule`](http://developer.softlayer.com/reference/services/SoftLayer_Network_Storage_Iscsi/enableSnapshots)
5. [`snapshot_capacity`](http://developer.softlayer.com/reference/services/SoftLayer_Network_Storage_Iscsi/getSnapshotCapacityGb)
6. [`os`](http://developer.softlayer.com/reference/services/SoftLayer_Network_Storage_Iscsi_OS_Type)
7. [`capacity`](http://developer.softlayer.com/reference/services/SoftLayer_Network_Storage_Iscsi/upgradeVolumeCapacity)

It would also need to include the relevant `get*` and methods to collect information necessary for making decisions.

Also implementing the necessary `remove*` methods to modify resources.

---
## Useful `softlayer-go` functions
1. [`softlayer-go/helpers/product/product.go`](https://github.com/softlayer/softlayer-go/blob/master/helpers/product/product.go)
## Items to implement
1. `softlayer-go/datatypes/network_storage.go`

**Comment by Freyert** [comment]
Here's an example of [using the billing](https://github.com/softlayer/terraform-provider-softlayer/blob/master/softlayer/resource_softlayer_bare_metal.go#L256):
1. create the [order template](https://github.com/softlayer/terraform-provider-softlayer/blob/master/softlayer/resource_softlayer_bare_metal.go#L266).
2. Place the [order](https://github.com/softlayer/terraform-provider-softlayer/blob/master/softlayer/resource_softlayer_bare_metal.go#L280).
3. [wait](https://github.com/softlayer/terraform-provider-softlayer/blob/master/softlayer/resource_softlayer_bare_metal.go#L288)

**Comment by Freyert** [comment]
Here's a helpful [StackOverflow post](http://stackoverflow.com/questions/35838651/api-for-listing-all-performance-storages-for-a-user) for getting all network storage associated with an account. Need a method for _user_ to uniquely identify these storage objects.

---

Essentially:
1. Account::getNetworkStorage
   - lists all network storage associated with an account.
   - add masks to get the information necessary to perform operations.
   - use a filter to find the exact storage item we're looking for.

---

in python:

``` python
import SoftLayer
client = SoftLayer.create_client_from_env(username='XXXXX', api_key='XXXXXX')
nas = client.call('Account', 'getNasNetworkStorage')
iscsi = client.call('Account', 'getIscsiNetworkStorage')
```

**Comment by Freyert** [comment]
https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/managers/storage_utils.py

**Comment by Freyert** [comment]
[Here's how the BOSH CPI team is creating the order using their version of the softlayer-go library](https://github.com/maximilien/softlayer-go/blob/90a945289f1f478e90874812491cd6cdf225e9e7/services/softlayer_network_storage.go#L68-L89)

**Comment by renier** [comment]
@Freyert You can do the same with the official softlayer-go:

``` go
    sess := session.New()

    order := datatypes.Container_Product_Order_Network_PerformanceStorage_Iscsi{
        Location: sl.String("wdc01"),  
        OsFormatType: &datatypes.Network_Storage_Iscsi_OS_Type{
            Id: sl.Int(12),
            keyName: sl.String("LINUX"),
        },
        Prices: []datatypes.Product_Item_Price{
            {Id: &sizeItemPriceId},
            {Id: &iopsItemPriceId},
            {Id: &blockStorageItemPriceId},
        },
        PackageId: &NETWORK_PERFORMANCE_STORAGE_PACKAGE_ID,
        Quantity: sl.Int(1),
        UseHourlyPricing: &useHourlyPricing,
    }

    service := services.GetProductOrderService(sess)
    receipt, err := service.PlaceOrder(&order, sl.Bool(false))
```

**Comment by Freyert** [comment]
Well, I've changed my mind I'm interested in ordering Endurance storage. I'm thinking there will have to be a separate resource for performance storage.

Also, when selecting sizes it's very difficult to figure out _which_ `20_GB_PERFORMANCE_STORAGE_SPACE` I need to choose. There are about 10-15 items with the same `keyName`. `locationId` and `capacityRestriction` seem to be the discerning factors here.

**Comment by renier** [comment]
@Freyert That's also considered network storage. The main two types of network storage is block storage and file storage. Then there are the flavors like endurance storage.

I would like to have two main resources: `softlayer_block_storage` (e.g. iSCSI) and `softlayer_file_storage`. Whether endurance flavor or not, that can be specified by the resource parameters.

**Comment by minsikl** [comment]
There are four different types of network storages except legacy NAS storage in SoftLayer. They require different options for storage configuration as follows: 

1) File performance storage - Provides NFS3, NFS4 with 1000 ~ 6000 IOPS option. Authorized hosts list should be managed. 
2) File endurance storage - Provides NFS3, NFS4 with 0.5 ~ 10 IOPS option. Also provides snapshot function. Authorized hosts list should be managed. 
3) Block performance storage - Provides iSCSI protocol with access credentials. OS Type and authorized hosts list should be managed.
4) Block endurance storage - Provides iSCSI protocol with access credentials. OS Type and authorized hosts list should be managed. Snapshot configuration and scheduling should be managed.

**Comment by Freyert** [comment]
Ah yeup, that's a better way to think about it.

**Comment by Freyert** [comment]
Ok, I've _finally_ figured out how to gather the bare minimum of items for these orders. For the first delivery I'm going to push a NetworkStorage resource, but it will only be able to interact with Endurance Block storage and ordering snapshot space for the store.

Hopefully I can easily leave it open to be extended, but yeesh all this is going to get cluttered with all these different storage types to support.

Are there plans to simplify SoftLayer's API further? This is really costly trying to figure out how to even use the API.

**Comment by Freyert** [comment]
Finally have an initial test somewhat working here, but I'm not quite sure how to tackle this error. Is it because I store the datacenter ID instead of the shortname?

```
TESTING FOR ITEM--- FAIL: TestAccSoftLayerNetworkStorage_Read (348.96s)
	resource_softlayer_network_storage_test.go:19: Running Resource Test
	testing.go:265: Step 0 error: After applying this step, the plan was not empty:

		DIFF:

		DESTROY/CREATE: softlayer_network_storage.test-iscsi
		  capacity_gb: "20" => "20"
		  create_date: "" => "<computed>"
		  datacenter:  "449494" => "dal09" (forces new resource)
		  iops:        "0.25" => "0.25"
		  nas_type:    "block" => "block"
		  notes:       "terraform_test" => "terraform_test"
		  os_type:     "LINUX" => "LINUX"
		  tier:        "endurance" => "endurance"

		STATE:

		softlayer_network_storage.test-iscsi:
		  ID = 16653243
		  capacity_gb = 20
		  datacenter = 449494
		  iops = 0.25
		  nas_type = block
		  notes = terraform_test
		  os_type = LINUX
		  tier = endurance
```

**Comment by renier** [comment]
@Freyert Hard to say without looking at some code. Is there implementation to back the test?

**Comment by Freyert** [comment]
@renier 

[Resource Network Storage](https://github.com/Freyert/terraform-provider-softlayer/blob/network_storage/softlayer/resource_softlayer_network_storage.go)
[Test](https://github.com/Freyert/terraform-provider-softlayer/blob/network_storage/softlayer/resource_softlayer_network_storage_test.go)

**Comment by renier** [comment]
Yes, I think it is because you change the datacenter to have the location id on Create. What happens if you omit that?

**Comment by Freyert** [comment]
@renier it worked! Question now is, what's the best way to make this more extensible to cover the rest of network storage available?

I'm imagining something along the lines of using a "switch" statement to switch on the drive "type". However, there's quite a range of possibilities here and the nuances of working with the ordering system are problematic as well.

Using this list of possible traits I'm imagining about 7 "paths" (possibly more):

1. endurance
  + block
  + file
2. performance
  + block
  + file
3. object storage

I think at some point though it might be beneficial to draw a line and have a different resource altogether as you'd be bundling a ton of functionality into one resource. Would probably also want to create a "library" to contain the commonly used functionality. Most of this functionality has to do with searching through Product_Packages so I'm sure other resources would benefit from it as well.

---

I'm game to work on making the code I've written more extensible and implementing the *endurance block* features that my team requires, but implementing the other items is not really on my docket. (Also, writing documentation)

It could be beneficial to draw up issues that explain some of the technical requirements and challenges in order to guide contributors towards implementing these features.

**Comment by renier** [comment]
@Freyert Object storage need not be covered here (there is already a related resource for that).

Two resources:
* softlayer_file_storage
* softlayer_block_storage (this issue)

Each one of those resources can have a `type` property to designated it as _performance_ or _endurance_ (which would enable/disable appropriate other properties like iops).

As for common code, that could potentially go in the helpers in _softlayer-go_ itself.

So if you can create a `softlayer_block_storage` resource that supports a type property (that could only accept _endurance_ for the time being) that is totally fine. Refactoring/decoupling common code can be done in later revisions.

**Comment by renier** [comment]
This is done. Thanks everyone for helping getting this in.
