### ISSUE TITLE
Add simple documentation for running acceptance tests.

### ISSUE THREAD

**Issue by Freyert** [softlayer/terraform-provider-softlayer#44]
I discovered terraform's official documentation on the matter, but it would probably help developers contribute if there was a link to that doc, a description of the environments that must be set, and how to run the tests.

I've gathered that these are the env variables from the official doc:
```
SOFTLAYER_USERNAME: Your SoftLayer username
SOFTLAYER_API_KEY: Your API key
```

but it would be good to add this to the documentation in order to accelerate the rate at which developers go from discovering this project, to contributing.

**Comment by Freyert** [comment]
@renier at the moment I'm a bit confused as to where [these functions](https://github.com/softlayer/terraform-provider-softlayer/blob/master/softlayer/resource_softlayer_bare_metal_test.go#L21-L22) are being imported. Or how I'm supposed to run these tests.

Ideally I would think `go test x_test.go` would work.

---

Gotta use `go test -run <REGEX>`.

**Comment by renier** [comment]
@Freyert In provider_test.go.

The Makefile has a testacc target for runnnig acceptance tests. There is a helpful comment there.

**Comment by Freyert** [comment]
```
export TESTARGS="-run NetworkStorage"
make testacc
```

[Setting the API user and Key.](https://github.com/softlayer/softlayer-go#sessions)

**Comment by renier** [comment]
@Freyert What would you recommend be added to the README?
