### ISSUE TITLE
Plugin not provides credentials on import

### ISSUE THREAD

**Issue by akaspin** [softlayer/terraform-provider-softlayer#45]
I'm trying to use terraform with SL. But I can't import existing infrastructure:

sl.tf :
```
provider "softlayer" {
  api_key = "<key>"
  username = "<user>"
}

resource "softlayer_ssh_key" "testkey1" {
  label = "testkey1"
  public_key = "${file("~/.ssh/id_rsa.pub")}"
}
```

Terraform apply works well:
```
$ terraform apply
softlayer_ssh_key.testkey1: Creating...
  fingerprint: "" => "<computed>"
  label:       "" => "testkey1"
  public_key:  "" => "ssh-rsa <...>\n"
softlayer_ssh_key.testkey1: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Key is created. But if I try to import - I got following error:

```
$ terraform import softlayer_ssh_key.testkey1 717079
2016/11/04 12:37:31 [INFO] Terraform version: 0.7.8  
2016/11/04 12:37:31 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.7.8/bin/terraform", "import", "-no-color", "softlayer_ssh_key.testkey1", "717079"}
...
2016/11/04 12:37:31 [INFO] Local softlayer provider configuration '/Users/spin/go/bin/terraform-provider-softlayer' overrides '/usr/local/Cellar/terraform/0.7.8/bin/terraform-TFSPACE-internal-plugin-TFSPACE-provider-TFSPACE-softlayer'
...
softlayer_ssh_key.testkey1: Refreshing state... (ID: 717079)
2016/11/04 12:37:31 [DEBUG] plugin: terraform-provider-softlayer: 2016/11/04 12:37:31 [DEBUG] Path:  https://api.softlayer.com/rest/v3/SoftLayer_Security_Ssh_Key/717079.json
2016/11/04 12:37:31 [DEBUG] plugin: terraform-provider-softlayer: 2016/11/04 12:37:31 [DEBUG] Parameters:
2016/11/04 12:37:32 [DEBUG] plugin: terraform-provider-softlayer: 2016/11/04 12:37:32 [DEBUG] Response:  {"error":"Access Denied. ","code":"SoftLayer_Exception_Public"}
...
2016/11/04 12:37:32 [DEBUG] vertex "provider.softlayer (close)", got dep: "softlayer_ssh_key.testkey1 (import id: 717079)"
Error importing: 1 error(s) occurred:

2016/11/04 12:37:32 [DEBUG] plugin: waiting for all plugin processes to complete...
* import softlayer_ssh_key.testkey1 (id: 717079): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.
...
```
[full log](https://github.com/softlayer/terraform-provider-softlayer/files/571350/tf.log.zip)

This also happens if I try to import any other resource.

UPD: Found workaround:

```
provider "softlayer" {
  api_key = "<api-key>"
  username = "<username>"
  endpoint_url = "https://<username>:<api-key>@api.softlayer.com/rest/v3"
}
```

**Comment by minsikl** [comment]
In order to import resources, the provider should be configured with environment variables. Please check the [Link](https://www.terraform.io/docs/import/usage.html). If `SL_USERNAME` and `SL_API_KEY` are configured as environment variables, the import will work.

**Comment by akaspin** [comment]
@minsikl I exported `SL_*` and `SOFTLAYER_*` before.

**Comment by minsikl** [comment]
@akaspin 
If `SL_*` is not configured, `terraform import` returns
`"No SoftLayer credentials were found. Please ensure you have specified them in the provider or in the environment (see the documentation)."`

If `SL_*` has right credentials but there is no resource or the user does not have proper privileges, `terraform import` returns 
`"Response:  {"error":"Unable to find object with id of '717079'." ,"code" : "SoftLayer_Exception_ObjectNotFound"}"`

if `SL_*` has wrong credentials, `terraform import` returns an error message `"{"error":"Access Denied. ","code":"SoftLayer_Exception_Public"}"`

I can see an error message `"{"error":"Access Denied,..."` in your log. It is necessary to check if `SL_*` or `SOFTLAYER_*` has right username and api_key.
