### ISSUE TITLE
[softlayer_virtual_guest] Cannot provision vm from custom image template with multiple disks

### ISSUE THREAD

**Issue by igoraj** [softlayer/terraform-provider-softlayer#50]
e.g. applying plan
```
resource "softlayer_virtual_guest" "vsi" {
    cores   = 1
    ram      = 1024
    disks    = [ 25, 10 ]
    name  = "test"
    domain = "domain.com"
    image_id = <custom image id>
    ssh_keys = [ "<some key>" ]
    datacenter = "osl01"
    local_disk = false
    hourly_billing = true
    private_network_only = true
}
```

Results in the following error:
```
Error applying plan:

1 error(s) occurred:

* softlayer_virtual_guest.vsi: Error creating virtual guest: SoftLayer_Exception_InvalidValue: Invalid value provided for 'blockDevices'. Block devices may not be provided when using an image template. (HTTP 500)
```

Further research shows that this is known issue:

- softlayer/softlayer-python/issues/693
- http://stackoverflow.com/questions/37128160/error-when-using-softlayer-ruby-api-to-specific-additional-disks-with-a-virtual

Any chance this will be supported through terraform using customOrder like described [here](http://sldn.softlayer.com/blog/bpotter/going-further-softlayer-api-python-client-part-3)?
Is there any other workaround that can be used in automated way (the only viable alternative right now is to manually order through Portal)?

**Comment by renier** [comment]
> Any chance this will be supported through terraform using customOrder like described here?

That would be a feature request. No plans to provide that at the moment. It would require a new custom order resource I think, or at least a custom virtual guest resource.

> Is there any other workaround that can be used in automated way (the only viable alternative right now is to manually order through Portal)?

You would have to code it. Using [softlayer-go](https://github.com/softlayer/softlayer-go) you could prepare the order with the right package id and the right prices for a virtual guest that points to an image template and has the additional disks.

**Comment by renier** [comment]
I'm reopening this issue and leaving like this for now. Currently, the feature most requested is this type of advanced ordering for bare metals, network storage, and now virtual guests.

In this case, I think the best thing would be to trigger the ordering logic based on the passed parameters (e.g. multiple disks). Contributions welcome.

**Comment by litch** [comment]
I just got bitten by this as well - it's going to make my life trying to use softlayer with terraform pretty awful, it looks like.  I would love to be able to start a virtual guest from one of my base images with multiple block devices - thanks.

**Comment by igoraj** [comment]
@renier i managed to get one of our devs look at this and prepare a PR, please review it and let us know if there is something else that we need to take care of to get this merged in.
