### ISSUE TITLE
Incompatible API version error

### ISSUE THREAD

**Issue by tomwganem** [softlayer/terraform-provider-softlayer#55]
This is an error I'm running into on my Mac, running 10.12.1. I can not replicate the error on a Ubuntu 16.04 machine.

I downloaded the terraform binary from terraform website. And used `go get -u github.com/softlayer/terraform-provider-softlayer` to install the terraform-provider-softlayer plugin. Now, whenever I do `terraform plan` I get this error

```
tomwganem:tf-ops-dev tomwganem$ terraform plan
[WARN] /Users/tomwganem/go/bin/terraform-provider-softlayer overrides an internal plugin for softlayer-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 2, Ours: 1
```

Some more info:
```
tomwganem:tf-ops-dev tomwganem$ go version
go version go1.7.3 darwin/amd64
tomwganem:tf-ops-dev tomwganem$ which terraform
/Users/tomwganem/go/bin/terraform
tomwganem:tf-ops-dev tomwganem$ terraform version
[WARN] /Users/tomwganem/go/bin/terraform-provider-softlayer overrides an internal plugin for softlayer-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
Terraform v0.7.13

tomwganem:tf-ops-dev tomwganem$ cat ~/.terraformrc
providers {
  dockerimage = "/Users/tomwganem/go/bin/terraform-provider-docker-image"
  softlayer   = "/Users/tomwganem/go/bin/terraform-provider-softlayer"
}
tomwganem:tf-ops-dev tomwganem$ git --git-dir=/Users/tomwganem/go/src/github.com/softlayer/terraform-provider-softlayer/.git rev-parse HEAD^
6204b5935fee97354a4c2ac7314eecf050329331
tomwganem:tf-ops-dev tomwganem$ terraform plan
[WARN] /Users/tomwganem/go/bin/terraform-provider-softlayer overrides an internal plugin for softlayer-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 2, Ours: 1
```

**Comment by renier** [comment]
@tomwganem Right, because the provider is not vendoring the terraform dependency, so go-get downloads the latest terraform from the master which is on version 0.8dev and builds against it. But the binary you downloaded is terraform is 0.7.x, thus the error.

Try the binary releases of the provider to get around this.

Unfortunately, this is how go-get works and we can't control that. We could strikethrough that instruction, until terraform releases 0.8 (but then it will happen again with 0.9). If you build your own terraform on 0.8, and go-get the provider, things should work.

Any suggestions? We could point to this issue from the README as well.

**Comment by tomwganem** [comment]
I built terraform from master using `make dev`. The issue is now resolved.

I think this issue is largely just me being unfamiliar with how the Go ecosystem works. Even still, I think it would be useful to make some sort of note in the README about what to expect when running `go get` to install the provider.

Here's my suggestion. 
> The `go get` installation method will check out the master branch from https://github.com/hashicorp/terraform to build with. If the terraform binary you are using is behind master, there could be an incompatibility. Considering rebuilding the terraform binary.
> ```
> cd ${GOPATH}/src/github.com/hashicorp/terraform && make dev
> ```
>  Alternatively, you could checkout the version of the terraform binary you are using and rebuild the provider.
> ```
> cd ${GOPATH}/src/github.com/hashicorp/terraform && git checkout v${TERRAFORM_BINARY_VERSION}
 > cd ${GOPATH}/src/github.com/softlayer/terraform-provider-softlayer && make bin
> ```
> Or try downloading one of the released binaries of provider.
