### ISSUE TITLE
Make softlayer_dns_domain target optional?

### ISSUE THREAD

**Issue by athak** [softlayer/terraform-provider-softlayer#61]
Hi,
Creating a new domain via this provider requires target to be set. This IP is also required when creating a domain via the portal. This IP address in turn is used to create an A record at the root of the domain.

However, when creating a domain via the softlayer command line client, the target is not required. The domain is created successfully without the A record. This leads me to believe that target could be optional?

Cheers,
Atha

**Comment by renier** [comment]
@athak We have someone working on this.
