### ISSUE TITLE
Support multiple IPv4 addresses

### ISSUE THREAD

**Issue by andrew-morris** [softlayer/terraform-provider-softlayer#65]
I'm not sure if this is a planned feature or something that already exists but it would be great if there was an exposed terraform config to allow adding multiple NICs to a node.

**Comment by minsikl** [comment]
SoftLayer vm provides one public network interface and one private network interface. If `private_network_only` is false in terraform configuration, the vm will have two network interfaces. Otherwise, the vm will have one private network interface.

**Comment by renier** [comment]
@minsikl Can you order a VM with multiple IPs from the portal? or can that only be done later with IP blocks?

**Comment by minsikl** [comment]
SoftLayer VM provides one private NIC and one public NIC. It is not possible to add additional virtual NICs to SoftLayer VMs. 

However, SoftLayer provides secondary IP addresses for VMs. They are public static IP addresses and can be ordered in VM creation menu. Once they are ordered together, a new VM will have secondary IP addresses as sub interfaces. Here is a result of secondary IP addresses:
```
eth0      Link encap:Ethernet  HWaddr 06:3e:59:97:1e:a4
          inet addr:10.86.107.133  Bcast:10.86.107.191  Mask:255.255.255.192
...

eth1      Link encap:Ethernet  HWaddr 06:70:fd:c5:a8:de
          inet addr:75.126.165.178  Bcast:75.126.165.191  Mask:255.255.255.240
...

eth1:0    Link encap:Ethernet  HWaddr 06:70:fd:c5:a8:de
          inet addr:75.126.14.4  Bcast:75.126.14.4  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:1    Link encap:Ethernet  HWaddr 06:70:fd:c5:a8:de
          inet addr:75.126.14.5  Bcast:75.126.14.5  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:2    Link encap:Ethernet  HWaddr 06:70:fd:c5:a8:de
          inet addr:75.126.14.6  Bcast:75.126.14.6  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:3    Link encap:Ethernet  HWaddr 06:70:fd:c5:a8:de
          inet addr:75.126.14.7  Bcast:75.126.14.7  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
```

eth0 and eth1 are primary NICs and eth1:0~eth1:3 are secondary public sub interfaces. In SoftLayer portal, secondary IP addresses can be configured in VM creation menu. However, VM modification menu does not support secondary IP address attachment and detachment. To add secondary IP addresses later, users should create IP blocks and manually configure sub interfaces or aliases on VMs.

**Comment by renier** [comment]
@andrew-morris Did you really mean explicit NICs? or just secondary IP addresses?

I think this would be a good feature to add @minsikl, so let's keep it around.

**Comment by andrew-morris** [comment]
Sorry- i didn't mean NICs. i just meant secondary ips

**Comment by minsikl** [comment]
The branch https://github.com/softlayer/terraform-provider-softlayer/tree/feature-virtual-guest-multipleips implemented` secondary_ip_count` and `secondary_ip_addresses` arguments for VM's secondary ip configurations.

**Comment by renier** [comment]
@andrew-morris You got your wish :-) Merry 🎄
