### ISSUE TITLE
Changing the domain_id of a softlayer_dns_domain_record should force recreation

### ISSUE THREAD

**Issue by athak** [softlayer/terraform-provider-softlayer#76]
Currently, changing the domain_id of a softlayer_dns_domain_record does not force recreation of the record which leads to unexpected behavior. The records are not removed from the "old" domain and are not created in the "new" domain either.

**Comment by renier** [comment]
@ivan-n16

**Comment by renier** [comment]
@athak does the merged #79 fix your issue?

**Comment by athak** [comment]
I apologize for the delay in replying. #79 fixes the issue. Thanks!
