### ISSUE TITLE
Can I order VM with monitoring and response configuration?

### ISSUE THREAD

**Issue by linsun** [softlayer/terraform-provider-softlayer#81]
when I order VM via terraform, can I order these service addons: host ping and tcp service monitoring, automated reboot from monitoring?

**Comment by renier** [comment]
@linsun Have you tried the basic_monitor resource? https://github.com/softlayer/terraform-provider-softlayer/blob/master/docs/resources/softlayer_basic_monitor.md

**Comment by linsun** [comment]
@renier thanks for the pointer, no, i haven't tried this.  From reading the docs, I see this can add basic monitor and notify a user, but how would it enable automated reboot?

**Comment by renier** [comment]
@linsun By specifying the response action. See http://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_Monitor_Version1_Query_ResponseType

**Comment by renier** [comment]
Actually, use this to get all the response action types: http://sldn.softlayer.com/reference/services/SoftLayer_Network_Monitor_Version1_Query_Host_Stratum/getAllResponseTypes

**Comment by linsun** [comment]
Thanks, do I need to install SL CLI or is there sample curl cmd to run to get all response types in your prior comment?

**Comment by renier** [comment]
@linsun You can use [Postman](https://www.getpostman.com/apps) as well. Not sure about SL CLI. Curl command is as you would expect (there are rest docs out there already), you just have to pass the username/apikey as part of the url.

```[
    {
        "actionDescription": "Do Nothing",
        "id": 1,
        "level": 0
    },
    {
        "actionDescription": "Notify Users",
        "id": 2,
        "level": 0
    },
    {
        "actionDescription": "Notify and Reboot",
        "id": 4,
        "level": 1
    },
    {
        "actionDescription": "Notify and Alert NOC",
        "id": 5,
        "level": 2
    },
    {
        "actionDescription": "Notify, Reboot and Alert NOC",
        "id": 6,
        "level": 2
    }
]```
