### ISSUE TITLE
Not able to create softlayer_lb_local_service_group

### ISSUE THREAD

**Issue by ghost** [softlayer/terraform-provider-softlayer#83]
Team,

I am having errors with no valuable information when trying to create a local loadbalancer.

```
# shares load balancer
resource "softlayer_lb_local" "shares_lb" {
  connections = 250
  datacenter  = "${var.cloud_conf["datacenter"]}"
  ha_enabled  = false
  dedicated   = false
}

# shares http load balancer group
resource "softlayer_lb_local_service_group" "shares_http_lb_group" {
  port             = 80
  routing_method   = "CONSISTENT_HASH_IP"
  routing_type     = "HTTP"
  load_balancer_id = "${softlayer_lb_local.shares_lb.id}"
  allocation       = 100
}
```

> * softlayer_lb_local_service_group.shares_http_lb_group: Error creating load balancer service group: SoftLayer_Exception_Public: Errors encountered when setting up the load balancer! Please contact customer service. (HTTP 200)

I have updated latest version of softlayer module and use terraform v0.8.4

Any ideas on how to debug this?

**Comment by minsikl** [comment]
@itsguy The tf configuration is correct. It looks like that the problem came from SoftLayer. Can you check if you are able to create the service group on SoftLayer portal?

**Comment by ghost** [comment]
It fails through the slcli with a key on a user that has super user..
```
guy$ slcli loadbal group-add --allocation 50 --port 80 --routing-type 2 --routing-method 10 local:188345
SoftLayerAPIError(SoftLayer_Exception_Public): Errors encountered when setting up the load balancer! Please contact customer service.
```

It also fails with the root account logged into the portal.   I will log a case for that.  

> Errors encountered when setting up the load balancer! Please contact customer service.

Not much details from the error messages from softlayer.  I assume you are just passing though the error message and that is all we got.

**Comment by renier** [comment]
@itsguy In addition to the ticket you open, you can also give it more visibility by posting it on stackoverflow tagged with _softlayer_.
