### ISSUE TITLE
Recreating tainted resource

### ISSUE THREAD

**Issue by bondyk** [softlayer/terraform-provider-softlayer#89]
If mark resource as tainted in terraform state file then next 'apply' destroys it and creates a new resource.

Wouldn't be better to trigger OS Reload in SoftLayer instead of doing two operations?

Moreover it would be nice to have this feature for the case when we have monthly VMs and at some point of time we want to re-use it for another customer. Destroy-create means that we order completely new VM and cancel old one in the middle of payed month.

**Comment by renier** [comment]
@bondyk That behavior falls under https://github.com/hashicorp/terraform/issues/1579 which seeks to have more granular control over the stages of a resource's life cycle. Within the current system, tainted resources must be destroyed on apply as there is no way for the existing resource code to untaint itself afaik. This is imposed by the current Terraform core logic.
