### ISSUE TITLE
Delete/recreate of virtual guest associated with LB causes error in update

### ISSUE THREAD

**Issue by blfreese** [softlayer/terraform-provider-softlayer#90]
Using Terraform to create two virtual machines, a load balancer with two groups, works correctly.  If the virtual machines are tainted and "terraform apply" run, an error occurs trying to find the LB services created earlier.

Terraform plan, after the taint, shows that the services should be modified and the VMs destroyed/recreated.  The services should be modified, but it appears they're being destroyed.

This is the last output:
softlayer_lb_local_service.test_lb_http_lb_services.0: Modifying...
  ip_address_id: "XXXXX549" => "XXXXX571"
softlayer_lb_local_service.test_lb_https_lb_services.0: Modifying...
  ip_address_id: "XXXXX549" => "XXXXX571"
softlayer_lb_local_service.test_lb_http_lb_services.1: Modifying...
  ip_address_id: "XXXXX557" => "XXXXX581"
softlayer_lb_local_service.test_lb_https_lb_services.1: Modifying...
  ip_address_id: "XXXXX557" => "XXXXX581"
Error applying plan:

4 error(s) occurred:

* softlayer_lb_local_service.test_lb_https_lb_services.0: Error retrieving load balancer service group from SoftLayer, SoftLayer_Exception_ObjectNotFound: Unable to find object with id of 'XXX061'. (HTTP 200)
* softlayer_lb_local_service.test_lb_https_lb_services.1: Error retrieving load balancer service group from SoftLayer, SoftLayer_Exception_ObjectNotFound: Unable to find object with id of 'XXX063'. (HTTP 200)
* softlayer_lb_local_service.test_lb_http_lb_services.0: Error retrieving load balancer service group from SoftLayer, SoftLayer_Exception_ObjectNotFound: Unable to find object with id of 'XXX121'. (HTTP 200)
* softlayer_lb_local_service.test_lb_http_lb_services.1: Error retrieving load balancer service group from SoftLayer, SoftLayer_Exception_ObjectNotFound: Unable to find object with id of 'XXX119'. (HTTP 200)

Example code:

    variable objcount {
          default = 2
     }

        variable "cloud_conf" {
          default = {
            username   = ""
            api_key    = ""
          }
        }

        provider "softlayer" {
          username = "${var.cloud_conf["username"]}"
          api_key  = "${var.cloud_conf["api_key"]}"
        }

        data "softlayer_image_template" "base_image" {
          name = "100GB - CentOS / CentOS / 6.0-64 Minimal for VSI"
        }

        resource "softlayer_virtual_guest" "machine" {
          count                    = "${var.objcount}"
          hostname                 = "lbtest-${count.index}"
          datacenter               = "sng01"
          domain                   = "XXXXXXXXXX"
          image_id                 = "${data.softlayer_image_template.base_image.id}"
          private_vlan_id          = "XXXXXXXXX"
          public_vlan_id           = "XXXXXXXX"
          network_speed            = "100"
          private_network_only     = "false"
          cores                    = "2"
          memory                   = "4096"
          local_disk               = "true"
          hourly_billing           = "true"
          dedicated_acct_host_only = "false"
        }

        # test_lb load balancer
        resource "softlayer_lb_local" "test_lb_lb" {
          connections = 250
          datacenter  = "sng01"
          ha_enabled  = false
          dedicated   = false
        }

        # test_lb http load balancer group
        resource "softlayer_lb_local_service_group" "test_lb_http_lb_group" {
          port             = 80
          routing_method   = "CONSISTENT_HASH_IP"
          routing_type     = "HTTP"
          load_balancer_id = "${softlayer_lb_local.test_lb_lb.id}"
          allocation       = 50
        }

        # test_lb https load balancer group
        resource "softlayer_lb_local_service_group" "test_lb_https_lb_group" {
          port             = 443
          routing_method   = "CONSISTENT_HASH_IP"
          routing_type     = "TCP"
          load_balancer_id = "${softlayer_lb_local.test_lb_lb.id}"
          allocation       = 50
        }

        # test_lb http load balancer group services
        resource "softlayer_lb_local_service" "test_lb_http_lb_services" {
          count             = "${var.objcount}"
          ip_address_id     = "${element(softlayer_virtual_guest.machine.*.ip_address_id_private, count.index)}"
          port              = 80
          enabled           = true
          service_group_id  = "${softlayer_lb_local_service_group.test_lb_http_lb_group.service_group_id}"
          weight            = 1
          health_check_type = "TCP"
        }

        # test_lb http load balancer group services
        resource "softlayer_lb_local_service" "test_lb_https_lb_services" {
          count             = "${var.objcount}"
          ip_address_id     = "${element(softlayer_virtual_guest.machine.*.ip_address_id_private, count.index)}"
          port              = 443
          enabled           = true
          service_group_id  = "${softlayer_lb_local_service_group.test_lb_https_lb_group.service_group_id}"
          weight            = 1
          health_check_type = "TCP"
        }

**Comment by minsikl** [comment]
When a virtual server is deleted, the related service is automatically deleted by SoftLayer. As a workaround, I changed the property of `ip_address_id` in `softlayer_lb_local_service` to `ForceNew`. If terraform needs to delete and create a vm, it will delete a service, delete the vm, create a new vm, and create a new service.
@blfreese, I created a branch [fix-lb-service](https://github.com/softlayer/terraform-provider-softlayer/tree/fix-lb-service) and added the fix. Can you test your configuration with this fix?

**Comment by blfreese** [comment]
I built a new provider based on your branch and if I taint one of the virtual server resources, all four LB services get marked for recreate (two are associated with the tainted machine, two are associate with a machine whose state is correct).

**Comment by minsikl** [comment]
Did you change .tf file, terraform.state, or real virtual server resource?

**Comment by blfreese** [comment]
No.  If I untaint the resource and run plan, terraform shows no changes. If
I taint one resource and run plan, it wants to change all four.

**Comment by minsikl** [comment]
Can you explain how you tainted the resource?

**Comment by blfreese** [comment]
terraform taint 'softlayer_virtual_guest.machine.0'

**Comment by blfreese** [comment]
Could the taint have to do with list reordering?  That is because we define the load balance services by a list, adding/removing changes the list so all services are recreated?

**Comment by minsikl** [comment]
It looks like that ``` "${element(softlayer_virtual_guest.machine.*.ip_address_id_private, count.index)}"``` does not detect a specific vm which has to be updated.

**Comment by renier** [comment]
So the way that Terraform sees what needs to be changed is affected by the undeterministic use of `*` in the `element()` function. Closing this.
